import { VatMode } from "@/shared/config/vat-options";

export type PayrollPeriodPreview = {
  key: string;
  label: string;
  date_from: string;
  date_to: string;
  is_current: boolean;
};

export type OrganizationProfile = {
  id: string;
  created_at: string;
  updated_at: string;
  display_name: string;
  legal_name: string;
  short_name?: string | null;
  legal_address?: string | null;
  mailing_address?: string | null;
  phone?: string | null;
  email?: string | null;
  inn?: string | null;
  kpp?: string | null;
  ogrn?: string | null;
  bank_name?: string | null;
  bik?: string | null;
  settlement_account?: string | null;
  correspondent_account?: string | null;
  recipient_name?: string | null;
  director_name?: string | null;
  accountant_name?: string | null;
  vat_mode: VatMode;
  vat_label: string;
  vat_rate_percent?: string | number | null;
  payroll_period_start_days: number[];
  payroll_periods_preview: PayrollPeriodPreview[];
  smtp_host?: string | null;
  smtp_port: number;
  smtp_username?: string | null;
  smtp_from_email?: string | null;
  smtp_from_name?: string | null;
  smtp_reply_to?: string | null;
  smtp_use_tls: boolean;
  smtp_use_ssl: boolean;
  smtp_password_configured: boolean;
  smtp_enabled: boolean;
  comment?: string | null;
};

export type OrganizationProfilePayload = {
  display_name: string;
  legal_name: string;
  short_name?: string;
  legal_address?: string;
  mailing_address?: string;
  phone?: string;
  email?: string;
  inn?: string;
  kpp?: string;
  ogrn?: string;
  bank_name?: string;
  bik?: string;
  settlement_account?: string;
  correspondent_account?: string;
  recipient_name?: string;
  director_name?: string;
  accountant_name?: string;
  vat_mode: VatMode;
  payroll_period_start_days: number[];
  smtp_host?: string;
  smtp_port: number;
  smtp_username?: string;
  smtp_password?: string;
  clear_smtp_password?: boolean;
  smtp_from_email?: string;
  smtp_from_name?: string;
  smtp_reply_to?: string;
  smtp_use_tls: boolean;
  smtp_use_ssl: boolean;
  comment?: string;
};
